### ISSUE TITLE
Error launching argos_worlds/construct.argos: libargos_ros_bot.so not found

### ISSUE THREAD

**Issue by pablogarciaaunon** [BOTSlab/argos_bridge#3]
After correctly launching _launch_demo.sh_, I have tried:

`argos3 -c argos_worlds/construct.argos`

With the following result:

```
[WARNING] Error opening directory "/home/pablo/catkin_ws/src/argos_bridge/ros_lib_links/": No such file or directory
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics2d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_spiri.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_footbot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_media.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_pointmass3d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_epuck.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_genericrobot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_entities.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_eyebot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3core_simulator.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_qtopengl.so"
[INFO] Not using threads
[INFO] Using random seed = 124
[INFO] Using simulation clock tick = 0.1
[INFO] Total experiment length in clock ticks = unlimited
[FATAL] Error initializing controllers
[FATAL] Can't load library "libargos_ros_bot.so" even after trying to add extensions for shared library (so) and module library (so): 
/usr/lib/argos3/libargos_ros_bot.so: /usr/lib/argos3/libargos_ros_bot.so: cannot open shared object file: No such file or directory
/usr/lib/argos3/libargos_ros_bot.so.so: /usr/lib/argos3/libargos_ros_bot.so.so: cannot open shared object file: No such file or directory
```

- Ubuntu 16.04
- ROS kinect
- Argos 3 working without ROS

**Comment by avardy** [comment]
I have an idea what may be the problem.  Did you take note of the following line in the README?

"The directory 'ros_lib_links' has a symbolic link to libroscpp.so. This may need to be updated for your system (most likely)."

Does that directory exist and have you made a symbolic link to libroscpp.so?

Andrew

**Comment by pablogarciaaunon** [comment]
Hello Andrew

You are right, the directory does not exists. I added the directory:

`ARGOS_PLUGIN_PATH=/opt/ros/kinetic/lib/`

(`libroscpp.so` is in that folder) having finally:

```
$ echo $ARGOS_PLUGIN_PATH
/opt/ros/kinetic/lib/:/home/pablo/catkin_ws/devel/lib
```

However, launching `argos_worlds/construct.argos`, I get a different error:

```
$ argos3 -c argos_worlds/construct.argos 
[INFO] Loaded library "/opt/ros/kinetic/lib/libgazebo_ros_template.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/librosconsole_log4cxx.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/libopencv_phase_unwrapping3.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/libinteractive_markers.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/librostime.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/liburdf.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/libmean.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/libopencv_bgsegm3.so"
[FATAL] Can't load library "/opt/ros/kinetic/lib/libgazebo_ros_laser.so" even after trying to add extensions for shared library (so) and module library (so): 
/opt/ros/kinetic/lib/libgazebo_ros_laser.so: libRayPlugin.so: cannot open shared object file: No such file or directory
/opt/ros/kinetic/lib/libgazebo_ros_laser.so.so: /opt/ros/kinetic/lib/libgazebo_ros_laser.so.so: cannot open shared object file: No such file or directory
/opt/ros/kinetic/lib/libgazebo_ros_laser.so.so: OK

```

I have also tried to add to `ARGOS_PLUGIN_PATH` the path where `libRayPlugin.so` is: `/usr/lib/x86_64-linux-gnu/gazebo-7/plugins`, with the same result.

Any idea what is going on?

Thanks

**Comment by dagarzonr** [comment]
Hi guys!

From [ARGoS's dev-manual](http://www.argos-sim.info/dev_manual.php):

''ARGoS is designed to look for user modules in any directory you list in the `ARGOS_PLUGIN_PATH` environment variable. For instance, if your development folder is `~/myargosstuff` and the binaries are all located in `~/myargosstuff/build`, you can set `$ export ARGOS_PLUGIN_PATH=$HOME/myargosstuff/build` and ARGoS will look for dynamic libraries in that directory. On Linux, ARGoS will look for `.so` files.''

So it is not a good idea to link the `ARGOS_PLUGIN_PATH` to` /opt/ros/kinetic/lib/`. This folder has too many libraries and ARGoS will attempt to load all of them. This can be observed in  @pablogarciaaunon 's post. There is no reason for loading Gazebo and OpenCV libraries.

```
[INFO] Loaded library "/opt/ros/kinetic/lib/libgazebo_ros_template.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/librosconsole_log4cxx.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/libopencv_phase_unwrapping3.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/libinteractive_markers.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/librostime.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/liburdf.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/libmean.so"
[INFO] Loaded library "/opt/ros/kinetic/lib/libopencv_bgsegm3.so"
[FATAL] Can't load library "/opt/ros/kinetic/lib/libgazebo_ros_laser.so" even after trying to add extensions for shared library (so) and module library (so): 
/opt/ros/kinetic/lib/libgazebo_ros_laser.so: libRayPlugin.so: cannot open shared object file: No such file or directory
/opt/ros/kinetic/lib/libgazebo_ros_laser.so.so: /opt/ros/kinetic/lib/libgazebo_ros_laser.so.so: cannot open shared object file: No such file or directory
/opt/ros/kinetic/lib/libgazebo_ros_laser.so.so: OK
```

Instead, the proper way to link `libroscpp.so` should be:

1. Create the folder `$HOME/catkin_ws/src/argos_bridge/ros_lib_links`.
2. ```export ARGOS_PLUGIN_PATH=$HOME/catkin_ws/src/argos_bridge/ros_lib_links```.
3. ```export ARGOS_PLUGIN_PATH=$ARGOS_PLUGIN_PATH:$HOME/catkin_ws/devel/lib```.
4. Create a link to the file `libroscpp.so`.
5. Move the link to the folder  `$HOME/catkin_ws/src/argos_bridge/ros_lib_links`.

However, I would like to ask @avardy why `libroscpp.so` should be linked? I think it should be enough to link `$HOME/catkin_ws/devel/lib` in the `ARGOS_PLUGIN_PATH`. Actually, if the link to `libroscpp.so` is removed, argos_bridge and ARGoS still work well.

Cheers,

**Comment by amberwood31** [comment]
Hi, guys

I've also had the same problem as @pablogarciaaunon . There are two things worth noting in the error message: 
1, error loading directory ros_lib_links, which can be fixed by doing exactly what @dagarzonr has suggested. Excellent clarification!
2, can't load the library libargos_ros_bot.so. This is the one I'm still having problems with. I assume it should be in the path $HOME/catkin_ws/devel/lib, but it's nowhere to be found. Also searched for it in usr/lib/argos3/, still nothing. Maybe something went wrong with the catkin_make? Any suggestion where I should be able to find this libargos_ros_bot.so?

Regards,

**Comment by amberwood31** [comment]
Updates: I've fixed my problem. 

As mentioned in the read_me：

> There is some issue in the order of building the messages in 'msg' and the argos plugin in 'plugin'. To resolve, comment out the following line in CMakeLists.txt:
add_subdirectory(plugin)
Go ahead and do 'catkin_make' then uncomment the line and do another 'catkin_make'. This should only occur once.

I misunderstood this as either commenting or uncommenting the line should work and ignored the error message when catkin_make with the line uncommented.

The proper way should be to run catkin_make with the line "add_subdirectory(plugin)" uncommented, since that's how the libargos_ros_bot.so would be generated. If you're like me and got error messages involving GSL, you probably haven't installed the GSL library. So go ahead and install the GSL library first. Then run catkin_make again. Another error I ran into here is "constexpr needed". Simply edit the argos_ros_bot.h file as suggested. Run catkin_make and then you should have libargos_ros_bot.so file in the dev/lib directory. 

Regards,

**Comment by pablogarciaaunon** [comment]
Thanks a lot guys! I finally made it work.

Regards,
Pablo

**Comment by avardy** [comment]
I'm so glad you guys have been able to figure these things out!  I'm afraid I'm a bit distant from this as I haven't used either argos or the argos_bridge in recent months.  But if anyone wants to make a suggestion (or issue a pull request) on what should be changed to alleviate these issues, please let me know.

**Comment by hahaha3214** [comment]
Hi,guys!
I've also had the same problem as @pablogarciaaunon  fixed it by doing exactly what @dagarzonr has suggested. However, launching argos_worlds/construct.argos, I get a different error:

-------------------------------------------------------------------------------------------
[FATAL] Can't load library "/home/argos3_t/devel/lib/libmaster_loop.so" even after trying to add extensions for shared library (so) and module library (so): 
/home/argos3_t/devel/lib/libmaster_loop.so: /home/argos3_t/devel/lib/libmaster_loop.so: undefined symbol: _Z13file_name_envB5cxx11
/home/argos3_t/devel/lib/libmaster_loop.so.so: /home/argos3_t/devel/lib/libmaster_loop.so.so: cannot open shared object file: No such file or directory
/home/argos3_t/devel/lib/libmaster_loop.so.so: OK
-------------------------------------------------------------------------------------------

Any idea what is going on?
Thanks

**Comment by hahaha3214** [comment]
Hi,guys!
I've also had the same problem as @pablogarciaaunon and fixed it by doing exactly what @dagarzonr has suggested. However, launching argos_worlds/construct.argos, I get a different error:
[FATAL] Can't load library "/home/argos3_t/devel/lib/libmaster_loop.so" even after trying to add extensions for shared library (so) and module library (so):
/home/argos3_t/devel/lib/libmaster_loop.so: /home/argos3_t/devel/lib/libmaster_loop.so: undefined symbol: _Z13file_name_envB5cxx11
/home/argos3_t/devel/lib/libmaster_loop.so.so: /home/argos3_t/devel/lib/libmaster_loop.so.so: cannot open shared object file: No such file or directory
/home/argos3_t/devel/lib/libmaster_loop.so.so: OK

Any idea what is going on?
Thanks

**Comment by lilin-ll** [comment]
Hi,guys!
I've also had the same problem as @pablogarciaaunon and fixed it by doing exactly what @dagarzonr has suggested. However, launching argos_worlds/construct.argos, I get a different error:

---------------------------------------------------------------------------------------------
**```
[FATAL] Can't load library "/home/argos3_t/devel/lib/libmaster_loop.so" even after trying to add extensions for shared library (so) and module library (so):
/home/argos3_t/devel/lib/libmaster_loop.so: /home/argos3_t/devel/lib/libmaster_loop.so: undefined symbol: _Z13file_name_envB5cxx11
/home/argos3_t/devel/lib/libmaster_loop.so.so: /home/argos3_t/devel/lib/libmaster_loop.so.so: cannot open shared object file: No such file or directory
/home/argos3_t/devel/lib/libmaster_loop.so.so: OK
```**
---------------------------------------------------------------------------------------------
Any idea what is going on?
Thanks
